### ISSUE TITLE
'NoneType' object has no attribute 'comments'

### ISSUE THREAD

**Issue by tylerknott** [PetterKraabol/Twitch-Chat-Downloader#61]
I followed the setup instructions but when I tried to run the program I got the following output:

```
$ python3 app.py --video 365612291 --format all --timezone UTC
Traceback (most recent call last):
  File "app.py", line 46, in <module>
    main()
  File "app.py", line 25, in main
    app.arguments.input = app.download(app.arguments.video, 'json')
  File "/home/tyler/py37test/Twitch-Chat-Downloader/app/downloader.py", line 27, in download
    lines, output = formats.use(format_name, video)
  File "/home/tyler/py37test/Twitch-Chat-Downloader/app/formats/formats.py", line 16, in use
    return _json.use(video)
  File "/home/tyler/py37test/Twitch-Chat-Downloader/app/formats/json.py", line 17, in use
    for comment in video.comments:
  File "/home/tyler/py37test/Twitch-Chat-Downloader/app/twitch/video.py", line 63, in comment_generator_from_api
    for comment in video.comments():
AttributeError: 'NoneType' object has no attribute 'comments'
```

It appears this is related to how the twitch.Helix.video() method is passing the input video ID to the twitch.helix.Videos class constructor.

I worked around this issue by changing the twitch.Helix.video() method to put the input video ID into a list when assigning to kwargs['id']:

```
    def video(self, video_id: Union[str, int] = None, **kwargs) -> 'helix.Video':
        if video_id:
            kwargs['id'] = [video_id]
        return helix.Videos(self.api(), video_ids=None, **kwargs)[0]
```

And by changing how the twitch.helix.Videos class constructor handles video IDs:

```
class Videos(Resource[helix.Video]):
    DEFAULT_FIRST: int = 20
    MAX_FIRST: int = 100

    def __init__(self,
                 api: API,
                 video_ids: Union[str, int, List[Union[str, int]]] = None,
                 **kwargs):
        super().__init__(api=api, path='videos')

        self._kwargs = kwargs

        if video_ids or 'id' in kwargs:
            if video_ids:
                self._kwargs['id'] = list(set(video_ids))
            self._download_video_ids(**self._kwargs)
        else:
            ...
```

However I'm not sure if this is the "correct" solution to this problem.

**Comment by PetterKraabol** [comment]
Thanks!

Caused by https://github.com/PetterKraabol/Twitch-Python/commit/15453b61fe062b0fb4693a82617371b741b26e75
I'm rewriting this commit, as I see some other potential issues and improvements.

**Comment by PetterKraabol** [comment]
Fixed in https://github.com/PetterKraabol/Twitch-Python/commit/1431c451424f43032921610aa616429580e55fee

`pip3 install --user twitch-python` for 0.0.11 and `git pull` tcd for new changes from https://github.com/PetterKraabol/Twitch-Chat-Downloader/commit/ec9fee5bf1a705291b988757c669138de549b5e8.
